### ISSUE TITLE
35kg servo? HTS-35H? 

### ISSUE THREAD

**Issue by samuk** [mgonzs13/ros2_rover#1]
Hi do you use this driver https://github.com/madhephaestus/lx16a-servo

Which supports this servo: https://www.hiwonder.hk/products/hiwonder-hts-35h-high-voltage-bus-servo-35kg-torque-with-data-feedback

**Comment by mgonzs13** [comment]
I have created my own driver for Python and C++ based on [probable-adventure](https://github.com/gadiego92/probable-adventure).

The servos used are similar to [these](https://www.amazon.com/LewanSoul-Real-Time-Feedback-Position-Temperature/dp/B073WR3SK9/ref=sr_1_7?crid=4AX5L53Q3VPK&keywords=LewanSoul&qid=1641246887&sprefix=lewansoul%2Caps%2C129&sr=8-7&th=1).

**Comment by samuk** [comment]
Thanks. I think it's likely that your driver would support the more powerful 35kg ones as well. 

The driver I linked above worked without changes. They are slightly larger, but obviously significantly more powerful.
