### ISSUE TITLE
[gzserver-2] [ERROR] [1707801034.985769425] [CompressedPublisher]: Compressed Image Transport - JPEG compression requires 8/16-bit color format (input format is: 32FC1)

### ISSUE THREAD

**Issue by er1c-cartman** [mgonzs13/ros2_rover#10]
Hi. while running the simulation, this error is keep happening
how can i solve this error?

[gzserver-2] [ERROR] [1707801034.985769425] [CompressedPublisher]: Compressed Image Transport - JPEG compression requires 8/16-bit color format (input format is: 32FC1)

or sometimes this error

[gzserver-2] [ERROR] [1707801031.596368729] [compressed_depth_image_transport]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: bgr8).

or this error

Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set.
[rgbd_odometry-3] rgbd_odometry subscribed to (approx sync, max interval=0.010000s):
[rgbd_odometry-3] /camera/image_raw,
[rgbd_odometry-3] /camera/depth/image_raw,
[rgbd_odometry-3] /camera/camera_info

Or this error

[rgbd_odometry-3] /camera/image_raw,
[rgbd_odometry-3] /camera/depth/image_raw,
[rgbd_odometry-3] /camera/camera_info
[rgbd_odometry-3] [WARN] [1707802340.214345119] [rgbd_odometry]: Odometry lost! Odometry will be reset after next 1 consecutive unsuccessful odometry updates...
[rgbd_odometry-3] [WARN] [1707802340.214421452] [rgbd_odometry]: Odometry automatically reset to latest odometry pose available from TF (odom->base_link)!
[rgbd_odometry-3] [WARN] [1707802340.969248403] [rgbd_odometry]: Odometry lost! Odometry will be reset after next 1 consecutive unsuccessful odometry updates...
[rgbd_odometry-3] [WARN] [1707802340.969301314] [rgbd_odometry]: Odometry automatically reset to latest odometry pose available from TF (odom->base_link)!
[rgbd_odometry-3] [WARN] [1707802343.813381359] [rgbd_odometry]: Odometry lost! Odometry will be reset after next 1 consecutive unsuccessful odometry updates...
[rgbd_odometry-3] [WARN] [1707802343.813481585] [rgbd_odometry]: Odometry automatically reset to latest odometry pose available from TF (odom->base_link)!

And when running the navigation in rviz, the robot is not moving smoothly on rviz. it's teleporting a lot
Like moving forward but suddenly goes back to initial position
Best regards

**Comment by er1c-cartman** [comment]
or sometimes this error

[gzserver-2] [ERROR] [1707801031.596368729] [compressed_depth_image_transport]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: bgr8).

**Comment by er1c-cartman** [comment]
or sometimes this error

"$ rostopic hz my_topic") and the timestamps in their header are set. 
[rgbd_odometry-3] rgbd_odometry subscribed to (approx sync, max interval=0.010000s):
[rgbd_odometry-3]    /camera/image_raw,
[rgbd_odometry-3]    /camera/depth/image_raw,
[rgbd_odometry-3]    /camera/camera_info

**Comment by mgonzs13** [comment]
I'm not sure why you are getting errors with Gazebo and the camera topics. Which ROS 2 distro are you using? Since they are compressed topics, this shouldn't affect the simulation.

The other messages are not errors but warnings. The rgbd_odometry node is telling you that one of those topics is not getting published messages. Check them using echo.

If the rover is "teleporting" may be due to slow localization processes, mainly in the RGB odometry, which may be produced by the bad performance of Gazebo. Which real factor are you getting in Gazebo?
