### ISSUE TITLE
Was Ackermann controller applied to this robot?

### ISSUE THREAD

**Issue by Mechazo11** [mgonzs13/ros2_rover#11]
Hi @mgonzs13 

Thank you very much for publicly releasing this project.

I was wondering, where you able to implement Ackermann drive controller with the simulated rover?

With best regards,
@Mechazo11

**Comment by mgonzs13** [comment]
Hi @Mechazo11, an Ackerman controller is used in both the real and the simulated rover. There are two versions: [vel_parser_node.cpp](https://github.com/mgonzs13/ros2_rover/blob/humble/rover_motor_controller_cpp/src/motor_controller/vel_parser_node.cpp) in C++ and [vel_parser_node.py](https://github.com/mgonzs13/ros2_rover/blob/humble/rover_motor_controller/rover_motor_controller/motor_controller/vel_parser_node.py) in Python.

**Comment by Mechazo11** [comment]
@mgonzs13 thank you very much for the prompt response. I will close this issue now.  I looked into your repo and if I am not mistaken, the simulation may have been setup for Gazebo Classic. For a class project I am working on, I might be able to upgrade the packages to Gazebo Harmonic. I will let you know if I do end up using your project as my starting point.
