### ISSUE TITLE
Interest in supporting BLDC motors?

### ISSUE THREAD

**Issue by samuk** [mgonzs13/ros2_rover#2]
Hi would you be interested in helping adapt this code for BLDC drive motors, whilst keeping the servo steering as it is? 

I hope this would give more power/control and improve waterproofing somewhat. The motors we're targeting are these [BGM2208'](https://www.aliexpress.com/item/1005001351533379.html)s but the drivers should support up to ~5A

The rough idea would be to use 3x [Rosmo ESC boards](https://github.com/rosmo-robot/Rosmo_ESC) & an [ESP32](https://github.com/rosmo-robot/Open-Core-M5stack#readme) 

We could either do Wifi or Ethernet from the Pi <> ESP32. It's all early days and the driver boards and I2C protocol are still under development, but I thought I'd drop you an email to see if it was something that appealed?

**Comment by mgonzs13** [comment]
It seems pretty interesting. You can send me an email to talk about this.

**Comment by samuk** [comment]
Email sent :)
