### ISSUE TITLE
running in simulation mode with gazebo

### ISSUE THREAD

**Issue by ROSRider** [mgonzs13/ros2_rover#6]
Hello,

Upon launching the software with `ros2 launch rover_bringup rover.launch.py` I get the following errors complaining about urg_node and lidar? I am just playing with the package, and I don't have access to a hokuyo, how can I bypass this step?

Best Regards,
C.

[urg_node_driver-1] [ERROR] [1645522381.047786768] [urg_node]: Error connecting to Hokuyo: Could not open serial Hokuyo:
[urg_node_driver-1] /dev/ttyACM0 @ 115200
[urg_node_driver-1] could not open serial device.

**Comment by mgonzs13** [comment]
```ros2 launch rover_bringup rover.launch.py``` is used in the real robot. You don't have to launch it with the gazebo simulator.
