### ISSUE TITLE
rover_motor_controller controller_node crashing with coredump

### ISSUE THREAD

**Issue by ROSRider** [mgonzs13/ros2_rover#7]
Hello,

The supplied custom controller with package is crashing with core dump.

Here is an excerpt:

[controller_node-4] terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
[controller_node-4]   what():  write_some: Bad file descriptor
[ERROR] [controller_node-4]: process has died [pid 113153, exit code -6, cmd '/home/can/ros2_foxy/install/rover_motor_controller_cpp/lib/rover_motor_controller_cpp/controller_node --ros-args -r __node:=controller_node --params-file /tmp/launch_params_hf8tz4lm'].

Here is another:

can@hurricane:~/ros2_foxy/src/ros2_rover/rover_bringup/launch$ /home/can/ros2_foxy/install/rover_motor_controller_cpp/lib/rover_motor_controller_cpp/controller_node
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  write_some: Bad file descriptor
Aborted (core dumped)

I am running on ubuntu20.04 - ros foxy.

Any ideas or help debugging this problem greatly appreciated.

Best Regards,
C.A.

**Comment by mgonzs13** [comment]
Are you running it in raspberry with the same hardware components ([motors](https://www.amazon.com/LewanSoul-Real-Time-Feedback-Position-Temperature/dp/B073WR3SK9/ref=sr_1_7?crid=4AX5L53Q3VPK&keywords=LewanSoul&qid=1641246887&sprefix=lewansoul%2Caps%2C129&sr=8-7&th=1))?

**Comment by ROSRider** [comment]
@mgonzs13 no. i am trying to run your software on a x64 ubuntu 20.04 regular computer. how can i fire the gazebo part, and experiment with it in simulation?

**Comment by mgonzs13** [comment]
If you want to run the simulator, you have to use the launch files from rover_gazebo. For instance, to launch the Moon world you have to use the command ```ros2 launch rover_gazebo moon.launch.py```. This will launch the Moon world, the rover simulator and RTAB. To move the rover use ```ros2 run rover_teleop teleop_keyboard_node``` in a new shell.
