### ISSUE TITLE
Ackermann in ROS2 control

### ISSUE THREAD

**Issue by samuk** [mgonzs13/ros2_rover#9]
I spotted this has just been merged: https://github.com/ros-controls/ros2_controllers/tree/master/tricycle_controller

Does that help anything here?

**Comment by mgonzs13** [comment]
I don't think this can be used directly on the rover since [it](https://github.com/ros-controls/ros2_controllers/blob/master/tricycle_controller/config/tricycle_drive_controller.yaml) uses only one front wheel.

The best option would be to create an Ackerman controller for six wheels.

**Comment by samuk** [comment]
OK no worries, just thought I'd mention it.
